import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import DashboardWrapper from "@/app/DashboardWrapper";

export const metadata: Metadata = {
  title: "Inventory Management App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
